services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: database
      CACHE_HOST: cache
      CACHE_PORT: 6379

  db:
    image: mariadb:lts
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p$MARIADB_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: database
    volumes:
      - db_data:/var/lib/mysql

  cache:
    image: valkey/valkey:latest
    restart: always
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6380:6379"
    volumes:
      - cache_data:/data

volumes:
  db_data:
  cache_data:
